# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Ui_mapeditor.ui'
#
# Created: Mon Aug 12 21:57:04 2013
#      by: PyQt4 UI code generator 4.10.2
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_Mapeditor(object):
    def setupUi(self, Mapeditor):
        Mapeditor.setObjectName(_fromUtf8("Mapeditor"))
        Mapeditor.resize(1223, 694)
        self.tab_1 = QtGui.QTabWidget(Mapeditor)
        self.tab_1.setGeometry(QtCore.QRect(990, 10, 211, 611))
        self.tab_1.setObjectName(_fromUtf8("tab_1"))
        self.map = QtGui.QWidget()
        self.map.setObjectName(_fromUtf8("map"))
        self.label = QtGui.QLabel(self.map)
        self.label.setGeometry(QtCore.QRect(60, 10, 81, 22))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setFocusPolicy(QtCore.Qt.NoFocus)
        self.label.setObjectName(_fromUtf8("label"))
        self.label_2 = QtGui.QLabel(self.map)
        self.label_2.setGeometry(QtCore.QRect(20, 540, 81, 21))
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.line = QtGui.QFrame(self.map)
        self.line.setGeometry(QtCore.QRect(10, 10, 51, 20))
        self.line.setFrameShape(QtGui.QFrame.HLine)
        self.line.setFrameShadow(QtGui.QFrame.Sunken)
        self.line.setObjectName(_fromUtf8("line"))
        self.line_2 = QtGui.QFrame(self.map)
        self.line_2.setGeometry(QtCore.QRect(140, 10, 51, 21))
        self.line_2.setFrameShape(QtGui.QFrame.HLine)
        self.line_2.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_2.setObjectName(_fromUtf8("line_2"))
        self.line_3 = QtGui.QFrame(self.map)
        self.line_3.setGeometry(QtCore.QRect(10, 460, 181, 20))
        self.line_3.setFrameShape(QtGui.QFrame.HLine)
        self.line_3.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_3.setObjectName(_fromUtf8("line_3"))
        self.delButton = QtGui.QPushButton(self.map)
        self.delButton.setGeometry(QtCore.QRect(30, 420, 141, 31))
        self.delButton.setObjectName(_fromUtf8("delButton"))
        self.cancelButton = QtGui.QPushButton(self.map)
        self.cancelButton.setGeometry(QtCore.QRect(30, 370, 141, 31))
        self.cancelButton.setObjectName(_fromUtf8("cancelButton"))
        self.comboBox_2 = QtGui.QComboBox(self.map)
        self.comboBox_2.setGeometry(QtCore.QRect(110, 540, 69, 22))
        self.comboBox_2.setObjectName(_fromUtf8("comboBox_2"))
        self.comboBox = QtGui.QComboBox(self.map)
        self.comboBox.setGeometry(QtCore.QRect(30, 490, 141, 31))
        self.comboBox.setObjectName(_fromUtf8("comboBox"))
        self.Button1_0 = QtGui.QRadioButton(self.map)
        self.Button1_0.setGeometry(QtCore.QRect(20, 40, 131, 31))
        self.Button1_0.setObjectName(_fromUtf8("Button1_0"))
        self.Button1_1 = QtGui.QRadioButton(self.map)
        self.Button1_1.setGeometry(QtCore.QRect(20, 80, 131, 31))
        self.Button1_1.setObjectName(_fromUtf8("Button1_1"))
        self.Button1_2 = QtGui.QRadioButton(self.map)
        self.Button1_2.setGeometry(QtCore.QRect(20, 120, 131, 31))
        self.Button1_2.setObjectName(_fromUtf8("Button1_2"))
        self.Button1_3 = QtGui.QRadioButton(self.map)
        self.Button1_3.setGeometry(QtCore.QRect(20, 200, 131, 31))
        self.Button1_3.setObjectName(_fromUtf8("Button1_3"))
        self.Button1_4 = QtGui.QRadioButton(self.map)
        self.Button1_4.setGeometry(QtCore.QRect(20, 160, 131, 31))
        self.Button1_4.setObjectName(_fromUtf8("Button1_4"))
        self.Button1_5 = QtGui.QRadioButton(self.map)
        self.Button1_5.setGeometry(QtCore.QRect(20, 240, 131, 31))
        self.Button1_5.setObjectName(_fromUtf8("Button1_5"))
        self.Button1_6 = QtGui.QRadioButton(self.map)
        self.Button1_6.setGeometry(QtCore.QRect(20, 280, 131, 31))
        self.Button1_6.setObjectName(_fromUtf8("Button1_6"))
        self.Button1_7 = QtGui.QRadioButton(self.map)
        self.Button1_7.setGeometry(QtCore.QRect(20, 320, 131, 31))
        self.Button1_7.setObjectName(_fromUtf8("Button1_7"))
        self.tab_1.addTab(self.map, _fromUtf8(""))
        self.unit = QtGui.QWidget()
        self.unit.setObjectName(_fromUtf8("unit"))
        self.label_3 = QtGui.QLabel(self.unit)
        self.label_3.setGeometry(QtCore.QRect(60, 10, 81, 22))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setFocusPolicy(QtCore.Qt.NoFocus)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.line_4 = QtGui.QFrame(self.unit)
        self.line_4.setGeometry(QtCore.QRect(10, 10, 51, 20))
        self.line_4.setFrameShape(QtGui.QFrame.HLine)
        self.line_4.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_4.setObjectName(_fromUtf8("line_4"))
        self.line_5 = QtGui.QFrame(self.unit)
        self.line_5.setGeometry(QtCore.QRect(140, 10, 51, 21))
        self.line_5.setFrameShape(QtGui.QFrame.HLine)
        self.line_5.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_5.setObjectName(_fromUtf8("line_5"))
        self.delButton_2 = QtGui.QPushButton(self.unit)
        self.delButton_2.setGeometry(QtCore.QRect(30, 480, 141, 31))
        self.delButton_2.setObjectName(_fromUtf8("delButton_2"))
        self.cancelButton_2 = QtGui.QPushButton(self.unit)
        self.cancelButton_2.setGeometry(QtCore.QRect(30, 420, 141, 31))
        self.cancelButton_2.setObjectName(_fromUtf8("cancelButton_2"))
        self.Button2_0 = QtGui.QRadioButton(self.unit)
        self.Button2_0.setGeometry(QtCore.QRect(20, 40, 131, 31))
        self.Button2_0.setObjectName(_fromUtf8("Button2_0"))
        self.Button2_1 = QtGui.QRadioButton(self.unit)
        self.Button2_1.setGeometry(QtCore.QRect(20, 80, 131, 31))
        self.Button2_1.setObjectName(_fromUtf8("Button2_1"))
        self.Button2_2 = QtGui.QRadioButton(self.unit)
        self.Button2_2.setGeometry(QtCore.QRect(20, 120, 131, 31))
        self.Button2_2.setObjectName(_fromUtf8("Button2_2"))
        self.Button2_3 = QtGui.QRadioButton(self.unit)
        self.Button2_3.setGeometry(QtCore.QRect(20, 160, 131, 31))
        self.Button2_3.setObjectName(_fromUtf8("Button2_3"))
        self.Button2_4 = QtGui.QRadioButton(self.unit)
        self.Button2_4.setGeometry(QtCore.QRect(20, 200, 131, 31))
        self.Button2_4.setObjectName(_fromUtf8("Button2_4"))
        self.Button2_5 = QtGui.QRadioButton(self.unit)
        self.Button2_5.setGeometry(QtCore.QRect(20, 240, 131, 31))
        self.Button2_5.setObjectName(_fromUtf8("Button2_5"))
        self.Button2_6 = QtGui.QRadioButton(self.unit)
        self.Button2_6.setGeometry(QtCore.QRect(20, 280, 131, 31))
        self.Button2_6.setObjectName(_fromUtf8("Button2_6"))
        self.Button2_7 = QtGui.QRadioButton(self.unit)
        self.Button2_7.setGeometry(QtCore.QRect(20, 320, 131, 31))
        self.Button2_7.setObjectName(_fromUtf8("Button2_7"))
        self.Button2_8 = QtGui.QRadioButton(self.unit)
        self.Button2_8.setGeometry(QtCore.QRect(20, 360, 131, 31))
        self.Button2_8.setObjectName(_fromUtf8("Button2_8"))
        self.tab_1.addTab(self.unit, _fromUtf8(""))
        self.saveButton = QtGui.QPushButton(Mapeditor)
        self.saveButton.setGeometry(QtCore.QRect(30, 300, 141, 31))
        self.saveButton.setObjectName(_fromUtf8("saveButton"))
        self.newButton = QtGui.QPushButton(Mapeditor)
        self.newButton.setGeometry(QtCore.QRect(30, 180, 141, 31))
        self.newButton.setObjectName(_fromUtf8("newButton"))
        self.saveasButton = QtGui.QPushButton(Mapeditor)
        self.saveasButton.setGeometry(QtCore.QRect(30, 360, 141, 31))
        self.saveasButton.setObjectName(_fromUtf8("saveasButton"))
        self.openButton = QtGui.QPushButton(Mapeditor)
        self.openButton.setGeometry(QtCore.QRect(30, 240, 141, 31))
        self.openButton.setObjectName(_fromUtf8("openButton"))
        self.exitButton = QtGui.QPushButton(Mapeditor)
        self.exitButton.setGeometry(QtCore.QRect(1030, 640, 141, 31))
        self.exitButton.setObjectName(_fromUtf8("exitButton"))

        self.retranslateUi(Mapeditor)
        self.tab_1.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(Mapeditor)

    def retranslateUi(self, Mapeditor):
        Mapeditor.setWindowTitle(_translate("Mapeditor", "Form", None))
        self.label.setText(_translate("Mapeditor", "地图元素", None))
        self.label_2.setText(_translate("Mapeditor", "<html><head/><body><p><span style=\" font-size:12pt; font-weight:600;\">放大倍数</span></p></body></html>", None))
        self.delButton.setText(_translate("Mapeditor", "删除", None))
        self.cancelButton.setText(_translate("Mapeditor", "撤销", None))
        self.Button1_0.setText(_translate("Mapeditor", "平原", None))
        self.Button1_1.setText(_translate("Mapeditor", "山地", None))
        self.Button1_2.setText(_translate("Mapeditor", "森林", None))
        self.Button1_3.setText(_translate("Mapeditor", "炮塔", None))
        self.Button1_4.setText(_translate("Mapeditor", "屏障", None))
        self.Button1_5.setText(_translate("Mapeditor", "陷阱", None))
        self.Button1_6.setText(_translate("Mapeditor", "神庙", None))
        self.Button1_7.setText(_translate("Mapeditor", "机关", None))
        self.tab_1.setTabText(self.tab_1.indexOf(self.map), _translate("Mapeditor", "地图", None))
        self.label_3.setText(_translate("Mapeditor", "士兵类型", None))
        self.delButton_2.setText(_translate("Mapeditor", "删除", None))
        self.cancelButton_2.setText(_translate("Mapeditor", "撤销", None))
        self.Button2_0.setText(_translate("Mapeditor", "剑士", None))
        self.Button2_1.setText(_translate("Mapeditor", "枪兵", None))
        self.Button2_2.setText(_translate("Mapeditor", "弓兵", None))
        self.Button2_3.setText(_translate("Mapeditor", "飞骑兵", None))
        self.Button2_4.setText(_translate("Mapeditor", "战士", None))
        self.Button2_5.setText(_translate("Mapeditor", "法师", None))
        self.Button2_6.setText(_translate("Mapeditor", "HERO_1", None))
        self.Button2_7.setText(_translate("Mapeditor", "HERO_2", None))
        self.Button2_8.setText(_translate("Mapeditor", "HERO_3", None))
        self.tab_1.setTabText(self.tab_1.indexOf(self.unit), _translate("Mapeditor", "士兵", None))
        self.saveButton.setText(_translate("Mapeditor", "保存", None))
        self.newButton.setText(_translate("Mapeditor", "新建", None))
        self.saveasButton.setText(_translate("Mapeditor", "另存为", None))
        self.openButton.setText(_translate("Mapeditor", "打开", None))
        self.exitButton.setText(_translate("Mapeditor", "返回", None))
